# Generated by Django 3.1.3 on 2020-12-18 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_quizzes',
        ),
    ]
