# Generated by Django 3.1.3 on 2020-12-18 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_question_type'),
        ('python_auth', '0002_remove_userprofile_created_quizzes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_quizzes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
    ]
