# Generated by Django 3.1.3 on 2020-12-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20201219_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='total_questions',
            field=models.IntegerField(null=True),
        ),
    ]
